# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Session-Store-File
version:      0.04
version_from: lib/Catalyst/Plugin/Session/Store/File.pm
installdirs:  site
requires:
    Cache::Cache:                  1.02
    Catalyst::Plugin::Session:     0.01
    Class::Accessor::Fast:         0.22
    Class::Data::Inheritable:      0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
