---
name: Catalyst-Plugin-Session-Store-File
version: 0.09
author:
  - 'Sascha Kiefer, L<esskar@cpan.org>'
abstract: |-
  File storage backend for
  session data.
license: perl
requires:
  Cache::Cache: 1.02
  Catalyst: 5
  Catalyst::Plugin::Session: 0.01
  Class::Accessor::Fast: 0.22
  Class::Data::Inheritable: 0.04
provides:
  Catalyst::Plugin::Session::Store::File:
    file: lib/Catalyst/Plugin/Session/Store/File.pm
    version: 0.09
generated_by: Module::Build version 0.2611
