--- #YAML:1.0
name:                Catalyst-Plugin-Session-Store-File
version:             0.11
abstract:            File storage backend for
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Cache::Cache:                  1.02
    Catalyst::Plugin::Session:     0.01
    Class::Accessor::Fast:         0.22
    Class::Data::Inheritable:      0.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Sascha Kiefer <esskar@cpan.org>
